/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcu;

import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero1 = new javax.swing.JTextField();
        numero2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        elareadelarea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        elcombito = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numero1.setText("0");
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        numero2.setText("0");
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel1.setText("calculadora mega-pro");

        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        elareadelarea.setColumns(20);
        elareadelarea.setRows(5);
        jScrollPane1.setViewportView(elareadelarea);

        jLabel2.setText("primer numero:");

        jLabel3.setText("segundo numero:");

        elcombito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "suma", "resta", "multiplicacion", "division", " n!", " X^y", " e^x", "10^x", "sen(x)", "cos(x)", "tan(x)", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(elcombito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(elcombito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = Integer.parseInt(numero1.getText()), y = Integer.parseInt(numero2.getText());
        if (x < y) {
            JOptionPane.showMessageDialog(null, " error: primer numero es menor a el segundo");
        }
        switch (elcombito.getSelectedIndex()) {
            case 0:
                numero2.setEditable(false);
                elareadelarea.append("\n" + " El resultado de la suma es: " + sum(x, y));
                break;
            case 1:
                numero2.setEditable(false);
                elareadelarea.append("\n" + " El resultado de la resta es: " + rest(x, y));
                break;
            case 2:
                numero2.setEditable(false);
                elareadelarea.append("\n" + " El resultado de la multiplicacion es: " + mult(x, y));
                break;
            case 3:
                numero2.setEditable(false);
                int a = div(x, y);
                elareadelarea.append("\n" + " El resultado division  es: " + a
                        + "\n" + " y el residuo es: " + rest(x, mult(y, a)));
                break;
            case 4:
                numero2.setEditable(true);
                int fact = 1;
                for (int i = 1; i <= x; i++) {
                    fact = mult(fact, i);
                }
                elareadelarea.append("\n" + " El resultado de el factorial  es: " + fact);
                break;
            case 5://x^y
                int elv = 1;
                for (int i = 1; i <= y; i++) {
                    elv = mult(elv, x);
                }
                elareadelarea.append("\n" + " El resultado  es: " + elv);
                break;
            case 6:
                double e = 0;
                int elva;
                for (int i = 0; i <= 7; i++) {
                     elva = 1;
                    for (int k = 1; k <= i; k++) {
                        elva = mult(elva, x);
                    }//potencia
                    System.out.println(""+elva);
                    int factq = 1;
                    for (int k = 1; k <= i; k++) {
                        fact = mult(factq, k);
                    }
                    e = sum2(e, div(elva, factq));

                }
                elareadelarea.append("\n" + " El resultado de e^" + x + " es:" + e);
                break;

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    int sum(int x, int y) {
        int r = x + y;
        return r;
    }

    double sum2(double x, double y) {
        double r = x + y;
        return r;
    }

    int mult(int x, int y) {
        int resu = 0;
        for (int i = 0; i < y; i++) {
            resu = sum(resu, x);
        }
        return resu;
    }

    double mult2(double x, double y) {
        double resu = 0;
        for (int i = 0; i < y; i++) {
            resu = sum2(resu, x);
        }
        return resu;
    }

    int div(int x, int y) {
        int resu = x, c = 0;
        while (resu > y) {
            resu = rest(resu, y);
            c++;
        }

        return c;
    }

    double div2(double x, double y) {
        double resu = x, c = 0;
        while (resu > y) {
            resu = rest2(resu, y);
            c++;
        }

        return c;
    }

    int rest(int x, int y) {
        int complemento = 10, contador = 0, result;
        while (y >= complemento) {
            complemento = mult(complemento, 10);
        }
        for (int i = y; i < complemento; i++) {
            contador++;
        }
        while (String.valueOf(x).length() > String.valueOf(contador).length()) {
            contador = Integer.parseInt("9" + contador);
        }
        result = Integer.parseInt(String.valueOf(sum(contador, x)).substring(1));
        System.out.println("" + result);
        return result;
    }

    double rest2(double x, double y) {
        double complemento = 10, contador = 0, result;
        while (y >= complemento) {
            complemento = mult2(complemento, 10);
        }
        for (double i = y; i < complemento; i++) {
            contador++;
        }
        while (String.valueOf(x).length() > String.valueOf(contador).length()) {
            contador = Integer.parseInt("9" + contador);
        }
        result = Integer.parseInt(String.valueOf(sum2(contador, x)).substring(1));
        return result;
    }
    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea elareadelarea;
    private javax.swing.JComboBox<String> elcombito;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    // End of variables declaration//GEN-END:variables
}
